name: Test custom image
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: github-arc-runners-podman
    steps:
    - run: echo "🎉 This job uses custom runner image with podman"
